# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/30b13abc-d20c-4578-8808-68be45485be3";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0A74-EC72";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/E074988F749869D4";
    fsType = "ntfs";
    options = [
      "rw"
      "nofail"
      "uid=1000"
      "gid=100"
    ];
  };

  fileSystems."/mnt/backup" = {
    device = "/dev/disk/by-uuid/5F8EAD8434E7B579";
    fsType = "ntfs";
    options = [
      "rw"
      "nofail"
      "uid=1000"
      "gid=100"
    ];
  };

  fileSystems."/mnt/games" = {
    device = "/dev/disk/by-uuid/70e29489-8d14-4285-9e64-4983d9718d21";
    fsType = "ext4";
    options = [
      "nofail"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
  programs.gpu-screen-recorder.enable = true;

  # graphics

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  # host name in network
  networking.hostName = "NixPC"; # Define your hostname.

}